### PR TITLE
Allow to use zope interface 4.7.1

### PR DESCRIPTION
**Pull request by bloodbare**

### CODE REVIEW

**Comment by bloodbare** [comment]
Fixes #733

**Comment by bloodbare** [comment]
@masipcat can you provide a test that fails? I don't understand were the error is.

**Comment by masipcat** [comment]
@bloodbare yes, working on it

**Comment by masipcat** [comment]
@bloodbare this test https://github.com/plone/guillotina/commit/290c0e83324d7c400ff6be20092f8c736be8c7db

**Comment by bloodbare** [comment]
@masipcat thanks, I've merged your PR and fixed, can you review again?

**Pull request merged**
