### PR TITLE
Catch invalid value types for registry modifications

### PR DESCRIPTION
**Pull request by pfreixes**
Backport for this [1]

[1] https://github.com/plone/guillotina/pull/981

### CODE REVIEW

**Comment by pfreixes** [comment]
@bloodbare there is a weird error with the CI [1], Ive tried to reproduce the error in local but it seems that there is something messed up with pytest coverage versions, any clue about what could be happening?

BTW, in local my branch and also the 5.x tests get frozen with this test

```
guillotina/tests/test_attachment.py::test_create_content_with_behavior[pyloop-redis]
```

Any idea why?


[1] https://travis-ci.org/github/plone/guillotina/builds/699223461

**Comment by lferran** [comment]
> @bloodbare there is a weird error with the CI [1], Ive tried to reproduce the error in local but it seems that there is something messed up with pytest coverage versions, any clue about what could be happening?
> 
> BTW, in local my branch and also the 5.x tests get frozen with this test
> 
> ```
> guillotina/tests/test_attachment.py::test_create_content_with_behavior[pyloop-redis]
> ```
> 
> Any idea why?
> 
> [1] [travis-ci.org/github/plone/guillotina/builds/699223461](https://travis-ci.org/github/plone/guillotina/builds/699223461)

@pfreixes Not sure, but probably it's downloading the redis/elastic/pg images while running the tests locally, and it appears as fronzen!

About the CI error, I think we need to upgrade pytest version because `pytest_cov` is requesting `>=4.6`.

Another solution would be to pin the previous versino of `pytest_cov` that works with current pytest version

**Comment by masipcat** [comment]
btw, it's funny that we run github actions on master and travis on branch 5.x

**Comment by pfreixes** [comment]
Pinning the `pytest-coverage` did not work either, seems that - if Im not missing something - that most of the test requirements are already satisfied [1], indeed its not respecting the version number restrictions provided at setup.py level.


[1] https://travis-ci.org/github/plone/guillotina/jobs/699285112#L359

**Comment by masipcat** [comment]
@pfreixes I think the pin should be `"pytest-cov>=2.0.0,<=2.9.0", `

**Comment by pfreixes** [comment]
well, spotted @masipcat Ill fix that too [1], just made a copy-paste from it :)

[1] https://github.com/plone/guillotina/pull/982/files#diff-2eeaed663bd0d25b7e608891384b7298L77

**Comment by pfreixes** [comment]
finally green!

**Comment by pfreixes** [comment]
Yeps, is there anything else that I should do for having this merged? and once is merged a patch version would be automatically released?

Thanks!

**Comment by vangheem** [comment]
5.3.46 released!

**Comment by pfreixes** [comment]
thanks man!

**Pull request merged**
