### PR TITLE
add argon2 pw hashing

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by jordic** [comment]
I'm not pretty sure, is this called on the thread pool. This is cpu bound...

```
In [5]: %time ph.hash("123412341234")                                                                                                                                                                                
CPU times: user 277 ms, sys: 60.2 ms, total: 337 ms
Wall time: 142 ms
Out[5]: '$argon2id$v=19$m=102400,t=2,p=8$k6HLUbEcypi9dskGVCa6xw$C6dKsKmaqWho1PZdrxZthQ'
```
If not, seems like could be something dangerous.. (Just someone hitting the logging endpoint)

**Comment by vangheem** [comment]
Alright, maybe we need to think about a different way to solve it.

salted SHA512 isn't ideal.

**Comment by vangheem** [comment]
or were you thinking we should move it to `run_in_executor`?

**Comment by jordic** [comment]
running the validators on a thread pool?

**Comment by vangheem** [comment]
Yes, we can do that. A specific thread pool with limited workers I think.

**Comment by jordic** [comment]
1 is enought, just to not be able to block the main thread.

**Comment by vangheem** [comment]
@jordic updated. Can you have a look?

**Pull request merged**
