### PR TITLE
Fix Command.__run() not waiting for all aio tasks to finish

### PR DESCRIPTION
**Pull request by masipcat**
Closes https://github.com/plone/guillotina/issues/463

### CODE REVIEW

**Comment by masipcat** [comment]
> So this will wait up to 1 second for each task?

Yes, I just kept the previous implementation but maybe we can try with asyncio.gather on all tasks without a timeout.

Do you want me to change the implementation with asyncio.gather?

**Comment by vangheem** [comment]
I think I'm okay leaving it. Could you maybe add a `logger.warning` if it exceeds the timeout? In the `asyncio.TimeoutError` exception handler?

**Comment by masipcat** [comment]
@vangheem done

**Comment by vangheem** [comment]
Thank you!

**Pull request merged**
