### PR TITLE
fix doc builds for open api 3

### PR DESCRIPTION
**Pull request by vangheem**
ref: https://github.com/plone/guillotina/issues/660

### CODE REVIEW

**Comment by svx** [comment]
Maybe it is because I am missing a package or something.
I just did a *fresh* checkout, switched to the *fix-doc-build*, repeating my steps from yesterday and getting the following output :)

```txt
Exception occurred:
  File "/home/svx/Projects/plone/guillotina/.venv/lib64/python3.7/site-packages/guillotina/documentation/sphinx/__init__.py", line 243, in run
    rst_content += "\n    :query {type} {name}: {description}".format(**parameter)
KeyError: 'type'
The full traceback has been saved in /tmp/sphinx-err-6l_5pt2t.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Exception ignored in: <function ClientSession.__del__ at 0x7fbac9d854d0>
Traceback (most recent call last):
  File "/home/svx/Projects/plone/guillotina/.venv/lib64/python3.7/site-packages/aiohttp/client.py", line 300, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BaseConnector.__del__ at 0x7fbaca04c560>
Traceback (most recent call last):
  File "/home/svx/Projects/plone/guillotina/.venv/lib64/python3.7/site-packages/aiohttp/connector.py", line 267, in __del__
  File "/home/svx/Projects/plone/guillotina/.venv/lib64/python3.7/site-packages/aiohttp/connector.py", line 414, in _close
  File "/home/svx/Projects/plone/guillotina/.venv/lib64/python3.7/site-packages/aiohttp/client_proto.py", line 62, in close
  File "/usr/lib64/python3.7/asyncio/selector_events.py", line 649, in close
  File "/usr/lib64/python3.7/asyncio/selector_events.py", line 266, in _remove_reader
  File "/usr/lib64/python3.7/selectors.py", line 190, in get_key
  File "/usr/lib64/python3.7/selectors.py", line 71, in __getitem__
  File "/usr/lib64/python3.7/selectors.py", line 225, in _fileobj_lookup
TypeError: 'NoneType' object is not callable
make: *** [Makefile:53: html] Error 2
```

**Comment by vangheem** [comment]
Ahh yeah. That's just noise from way aiohttp shuts down.

If you do a echo $? You should see that it's finished and docs built

**Comment by vangheem** [comment]
@svx docs building again on readthedocs: https://guillotina.readthedocs.io/en/latest/

Thank you!

**Comment by vangheem** [comment]
@svx sorry, I read your traceback closer and yah, that looks like a failure.

It doesn't look like you have the changes though...

From the looks of it, maybe you did `pip install .` instead of using `pip install -e .` for guillotina.

Install path is referencing python installing, not the git clone directory: `/home/svx/Projects/plone/guillotina/.venv/lib64/python3.7/site-packages/guillotina/documentation/sphinx/__init__.py`

**Comment by svx** [comment]
@vangheem Yes! That was it!

Thanks!

I will think about a logical place in the docs/README (not sure yet) and create a PR!

Thanks again!!!

**Pull request merged**
