### PR TITLE
Use orjson 3.x

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

As `orjson` 3.x has many fixes, see https://github.com/ijl/orjson/releases, I can suggest to use this version instead of **2.6.0**

Besides, it will fix https://github.com/the-benchmarker/web-frameworks/pull/3600

Regards,

### CODE REVIEW

**Comment by masipcat** [comment]
I think @bloodbare wanted to wait for G7 to upgrade this deps. We'll start G7 development in the following weeks. Maybe we can  use that version for the benchmark

**Comment by bloodbare** [comment]
We can update it on 6.X , I've verified that does not break anything!

**Comment by bloodbare** [comment]
@waghanza you should sign Plone contribution agreement and modify the changelog to have a valid PR.

**Comment by waghanza** [comment]
Sure @bloodbare. I'll check how to create a proper changelog entry

**Comment by masipcat** [comment]
> > @waghanza you need to sign the Plone Contributor Agreement in order to merge this pull request.
> > Learn about the Plone Contributor Agreement: http://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html
> 
> done @mister-roboto

can you push another commit to trigger the bot, please?

**Comment by waghanza** [comment]
@masipcat I thought I've signed the agreement

**Comment by ableeb** [comment]
Close then reopen this PR to get the robot to rescan for your contributors agreement

**Pull request closed without merging**
