### PR TITLE
[master] Add `clear` patch field operation and provide `max_ops` property to patch fields

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
It should be increased. Everything is covered and I added extra tests for things not covered. I can check later but maybe the report is wrong.

**Comment by bloodbare** [comment]
> It should be increased. Everything is covered and I added extra tests for things not covered. I can check later but maybe the report is wrong.

Thanks why I was commenting, I saw a red coverage but I can't see in code why

**Comment by vangheem** [comment]
I don't understand the report. If you look at https://codecov.io/gh/plone/guillotina/pull/897/diff -- with what I touched, I should have better coverage...

**Comment by vangheem** [comment]
I wonder if it does a bad job handling cherry pick? I'm merging. The reports everywhere on codecov do not make sense.

**Pull request merged**
