### PR TITLE
ship Executioner with Guillotina

### PR DESCRIPTION
**Pull request by ebrehault**
Note: If you think we must ship it as an external package, let me know.

### CODE REVIEW

**Comment by ebrehault** [comment]
> If there any way to ship where the svg files are combined?

I am not sure I understand, do you mean here https://github.com/plone/guillotina/tree/master/static/brand ?

> I'm going to tweak this so the files are in the python module and can be used from other contexts without needing to know the full path.

Ok, does it implies the publication path is not necessarily `/+admin/`? If so, we'll need to change the Angular build.

**Comment by vangheem** [comment]
I'm sorry "if" should have been "is".

It will still be served from same URL so we're good!

**Comment by ebrehault** [comment]
So I just have to move `/static/executioner` to `/static/brand/executioner`, right?

**Comment by vangheem** [comment]
I fixed with: https://github.com/plone/guillotina/pull/311/commits/2bb5edf7cb3e505ea67a69b56f541d77acb43e8f

**Pull request merged**
