### PR TITLE
Fix command 'create'

### PR DESCRIPTION
**Pull request by masipcat**

### CODE REVIEW

**Comment by vangheem** [comment]
How come this is necessary? Create is for cookie cutter. We don't need app in that case right?

**Comment by masipcat** [comment]
It's needed because I moved the app.startup() to the AsgiApp to make the initialization work when running guillotina using a asgi server directly (without calling the command 'server').

**Comment by masipcat** [comment]
But I think we could rethink this part. Also how we manage the settings/config_file and the app lifecycle.

**Comment by vangheem** [comment]
gotcha

**Pull request merged**
