### PR TITLE
Heroku install? #337

### PR DESCRIPTION
**Pull request by karannaoh**
[heroku deployement](https://testguillotina.herokuapp.com/)

### CODE REVIEW

**Comment by kakshay21** [comment]
#337

**Comment by vangheem** [comment]
Is there anything more we can do about configuring it?

How are postgresql settings provided for example?

**Comment by vangheem** [comment]
Also, would you be able to sign the plone contributor agreement? Thank you!

**Comment by karannaoh** [comment]
hey @vangheem you can provide a config.yaml with the correct details about PostgreSQL(which you need to deploy on heroku before deploying guillotina) details in config.yaml file will be different for different deployments(will change according to PostgreSQL deployed)

**Comment by karannaoh** [comment]
@vangheem I have signed and mailed plone contributor agreement

**Pull request closed without merging**
