### PR TITLE
fix some confuse docs

### PR DESCRIPTION
**Pull request by jordic**

### CODE REVIEW

**Comment by vangheem** [comment]
is it still wip?

**Comment by jordic** [comment]
Yes, will try to add some more examples!

**Comment by vangheem** [comment]
Can we merge as it is?

**Comment by vangheem** [comment]
@jordic ^^

**Comment by masipcat** [comment]
https://github.com/plone/guillotina/issues/674

**Comment by jordic** [comment]
Yup, could be merged!
Ideally, when I have enought time, it will have an examples folder inside the guillotina, with common use case (Thought the only one we have is the chat).

**Comment by vangheem** [comment]
Okay! Merging and we can add more later. Thank you!

**Pull request merged**
