### PR TITLE
fix catalog interface

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by masipcat** [comment]
@vangheem did you see this comment https://github.com/plone/guillotina/pull/535/files#r294730206 ?

**Comment by vangheem** [comment]
@masipcat thank you for reminding me! Sorry, I've had a lot of messages to process and my queue is backed up :)

**Comment by vangheem** [comment]
@masipcat can you review now?

**Comment by masipcat** [comment]
@vangheem no worries :-) If I'm not misunderstanding what this code is doing, you'll need to change the table name `'objects'` to  `PostgresStorage._object_table_name` :

 https://github.com/plone/guillotina/blob/7621ab772f209e12be4e85fd57300d5f5ec32e86/guillotina/contrib/catalog/pg.py#L194-L200

**Comment by vangheem** [comment]
ooops! I Missed that one too. Sorry! I'll take care!

**Comment by masipcat** [comment]
LGTM!

**Comment by vangheem** [comment]
@masipcat thank you for reviewing! Good catch!

**Pull request merged**
