### PR TITLE
Adding = to valid chars

### PR DESCRIPTION
**Pull request by bloodbare**

### CODE REVIEW

**Comment by vangheem** [comment]
uh oh, we need to disable mr.roboto here.

**Comment by vangheem** [comment]
@bloodbare why `=`? I mean, I guess it's fine but an `=` is also used for query params so it'll never look nice in a url.

**Comment by vangheem** [comment]
and changelog!

**Comment by bloodbare** [comment]
I want to store base64 urls

**Comment by vangheem** [comment]
Wwwaaaahh? Haha, ok :)

**Pull request merged**
