### PR TITLE
Config file path

### PR DESCRIPTION
**Pull request by cdevienne**

### CODE REVIEW

**Comment by cdevienne** [comment]
Hi @vangheem, it seems this feature disappeared in 2.5.x, is it on purpose?

**Comment by cdevienne** [comment]
It's actually in 3.0.0a1 that __file__ is absent of app_settings.

**Comment by vangheem** [comment]
I see it here: https://github.com/plone/guillotina/blob/master/guillotina/commands/__init__.py#L68

**Comment by vangheem** [comment]
@cdevienne gotcha. Nevermind.

**Comment by cdevienne** [comment]
After an upgrade the entry was not present when starting a service.
I reverted to 2.5 (and master) anyway, so I am good for now.

**Pull request merged**
